### ISSUE TITLE
Adapter funktioniert nicht mehr.

### ISSUE THREAD

**Issue by bahnuhr** [frankjoke/ioBroker.bmw#11]
Adapter funktioniert nicht mehr.

Genauer die Funktionen:
Klima, Auto auf/zu, lichthupe, etc.

siehe auch thread:
https://forum.iobroker.net/topic/22085/bmw-adapter-funktioniert-der-noch

**Comment by bahnuhr** [comment]
Achtung an alle !!!!!!!

1.4.0 hat einen BUG!

Zumindest bei mir

Es erfolgt kein debug; und der Adapter funktioniert auch nicht.

Die Version 1.3.3. wurde mir auch nicht mehr im Expertenmodus angeboten.

Habe die komplette Version gelöscht und mit:

npm i iobroker.bmw@1.3.3 --production

die "alte" version wieder installiert.

Hier funktioniert der Adapter wieder. Auch der debug.

vgl. auch o.g. thread.

**Comment by frankjoke** [comment]
Der Adapter hat nur eine neue Konfig (braucht admin 3) . 
Bitte Probleme im Forum unter https://forum.iobroker.net/topic/7457/adapter-bmw-zum-auslesen-von-bmw-s-connecteddrive-daten melden!

**Comment by bahnuhr** [comment]
admin 3 hab ich schon lange drauf.
