### ISSUE TITLE
Mini Connected?

### ISSUE THREAD

**Issue by zeron850** [frankjoke/ioBroker.bmw#25]
Hallo,

ist es nicht möglich auch Mini Fahrzeuge mit den Adapter auszulesen? Es kommt immer eine "requested" Fehlermeldung und er zeigt keine Daten und das Fahrzeug im iobroker an. Brauchst man dazu eine andere url in den Adapter Einstellungen?

**Comment by frankjoke** [comment]
Hallo!
Leider kann ich das nicht testen da ich keinen Mini habe und auch nicht die dazugehörige web-app kenne!
Damit kann ich das nicht testen. 
Schalte debug bei dem Adapter ein und zeige welche Meldungen dann beim Adapterstart im log kommen! p.s.: Bitte im Forum solche Fragen stellen: https://forum.iobroker.net/topic/7457/adapter-bmw-zum-auslesen-von-bmw-s-connecteddrive-daten

**Comment by zeron850** [comment]
Hallo,
ich habe es jetzt getestet und folgendes kann ich dir mitteilen:

`
bmw.1 | 2020-08-09 09:58:05.136 | info | (10862) BMW Adapter initialization finished, will scan ConnectedDrive every 60 minutes.
-- | -- | -- | --
bmw.1 | 2020-08-09 09:58:05.068 | warn | (10862) Error in GetCars, most probably the server is down! No data is  changed:  RequestVehicles Error to get data for Vehicles : { Error:  getaddrinfo ENOTFOUND https://www.mini.de/de_DE/home/connect
bmw.1 | 2020-08-09 09:58:05.062 | warn | (10862) BMWrequest error on path /api/me/vehicles/v2: { Error:  getaddrinfo ENOTFOUND  https://www.mini.de/de_DE/home/connected/my-mini-data.html  https://www.mini.de/de_DE/home/connected/my-mini-data.h
bmw.1 | 2020-08-09 09:58:04.418 | info | (10862) BMW will scan the following services: efficiency, dynamic,  navigation, remote_execution, remote_chargingprofile, remote_history,  servicepartner, service, specs, store, map_download.
bmw.1 | 2020-08-09 09:58:02.920 | warn | (10862) adapter.objects.getObjectList is deprecated, and will be  removed in the future. Please use adapter.getObjectList/Async. Report  this to Developer!
bmw.1 | 2020-08-09 09:58:02.597 | warn | (10862) adapter.objects.getObjectList is deprecated, and will be  removed in the future. Please use adapter.getObjectList/Async. Report  this to Developer!
bmw.1 | 2020-08-09 09:58:02.549 | info | (10862) starting. Version 1.3.3 in /opt/iobroker/node_modules/iobroker.bmw, node: v10.21.0, js-controller: 3.1.6

`
Ich habe auch alles hier beschrieben:
https://forum.iobroker.net/topic/7457/adapter-bmw-zum-auslesen-von-bmw-s-connecteddrive-daten/169 
Kannst du dir das mal ansehen? DANKE
