### ISSUE TITLE
Adapter geht nicht mehr - Code 404

### ISSUE THREAD

**Issue by bahnuhr** [frankjoke/ioBroker.bmw#32]
https://forum.iobroker.net/topic/40001/bmw-adapter-code-404

**Comment by molkemolko** [comment]
Hi, gleiches Problem bei mir. Leider scheint die API für Remote Services geändert worden zu sein. Wäre mega, wenn das gefixt werden könnte. :)

**Comment by molkemolko** [comment]
Vielleicht könnte das hier helfen, für Home Assistant wurde das bereits gefixt, lag tatsächlich an der API Änderung: https://community.home-assistant.io/t/bmw-connected-drive-doesnt-work-anymore/237983

**Comment by bahnuhr** [comment]
Danke.
Mit dem Link komme ich nicht so klar.
Wäre schön, wenn du den Adapter bei iob auch richtig stellen könntest.
Benutze diesen jeden Tag um die Klima einzuschalten.
Danke im Voraus.
mfg
Dieter

**Comment by molkemolko** [comment]
Ich bin nicht der Entwickler, sondern habe das gleiche Problem und wollte das hier zum Einen als Hilfe für den Entwickler posten und zum Anderen könnte man, wenn man denn will, sich zweitweise mit einer Home Assistant Installation helfen, in der man das BMW Plugin installiert und dann per iob Adapter darauf zugreift. Letzteres habe ich aber selber noch nicht probiert. LG Malte

**Comment by bahnuhr** [comment]
du schreibst:
in der man das BMW Plugin installiert und dann per iob Adapter darauf zugreift. 

Könntest du dies näher beschreiben wie das funktionieren soll.
Danke.

**Comment by bahnuhr** [comment]
keine Reaktion vom Entwickler.
Adapter habe ich eben gelöscht.
Fazit: 
Adapter funktioniert nicht mehr.
