### ISSUE TITLE
New Issue

### ISSUE THREAD

**Issue by zeron850** [frankjoke/ioBroker.bmw#54]
ioBroker: Eintrag in Protokolle: Log: error - bmw.0","message":"(134884) {\"statusCode\":404,\"message\":\"Resource not found\"}","ts":1688209951383},{"date":"Heute 13:12","severity":"<span class='logError logSeverity'>error</span>","from":"bmw.0","message":"(134884) AxiosError: Request failed with status code 404","ts":1688209951382},{"date":"Heute 13:12","severity":"<span class='logError logSeverity'>error</span>","from":"bmw.0","message":"(134884) getvehicles v2 failed","ts":1688209951376}]

**Comment by kenzo398** [comment]
Similar issue sine one week:

| error | {"statusCode":404,"message":"Resource not found"}
| error | AxiosError: Request failed with status code 404
| error | getvehicles v2 failed

**Comment by samazw** [comment]
> Similar issue sine one week:
> 
> | error | {"statusCode":404,"message":"Resource not found"} | error | AxiosError: Request failed with status code 404 | error | getvehicles v2 failed

same here since two weeks:

--
{"statusCode":404,"message":"Ressource not found"}
AxiosError: Request failed with Statuscode 404
getvehicles v2 failed
--

Restart of adapter has no effect.

**Comment by BastiX456** [comment]
same here since some weeks:

bmw.0 | 2023-07-10 08:51:08.397 | error | {"statusCode":404,"message":"Resource not found"}
bmw.0 | 2023-07-10 08:51:08.397 | error | AxiosError: Request failed with status code 404
bmw.0 | 2023-07-10 08:51:08.397 | error | getvehicles v2 failed

**Comment by tollertenya** [comment]
error | {"statusCode":404,"message":"Resource not found"}
error | AxiosError: Request failed with status code 404
error | getvehicles v2 failed

Same here - hope can be fixed

**Comment by tollertenya** [comment]
Fixed in https://github.com/TA2k/ioBroker.bmw 2.6.1
