### ISSUE TITLE
Add Support for Compact mode (js-Controller 2.0 Feature)

### ISSUE THREAD

**Issue by ldittmar81** [frankjoke/ioBroker.bmw#7]
The upcoming version 2.0.0 of js-controller will support a new mode for low memory devices. For this, a few minor adjustments to the adapter must be made. Please follow these instructions: https://forum.iobroker.net/viewtopic.php?f=24&t=20387#p213466

**Comment by frankjoke** [comment]
I work on this in the next weeks ...

**Comment by frankjoke** [comment]
Should work also, but still did not get info from you how to setup a test system where I can test if compact mode is working for my adapters (new js-controller...)
All my attempts to use beta-controller destroyed iobroker-installation immediately.
